version: "3.9"

services:
  rag-ingest:
    build:
      context: .
      dockerfile: services/rag_ingest/Dockerfile
    container_name: rag-ingest
    volumes:
      - ./.faiss_vs:/app/.faiss_vs
      - ./data:/app/data
    environment:
      - DATA_DIR=/app/data/student_profile
      - VECTOR_DIR=${VECTOR_DIR}
      - INDEX_NAME=${INDEX_NAME}
      - EMBEDDINGS_PROVIDER=${EMBEDDINGS_PROVIDER}
      - EMBEDDINGS_MODEL=${EMBEDDINGS_MODEL}
      - HF_EMBED_MODEL=${HF_EMBED_MODEL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    restart: "no"

  rag-api:
    build:
      context: .
      dockerfile: services/rag_api/Dockerfile
    container_name: rag-api
    depends_on:
      - rag-ingest
    ports:
      - "8002:8000"
    volumes:
      - ./.faiss_vs:/app/.faiss_vs
    environment:
      - SERVICE_MODE=local
      - VECTOR_DIR=${VECTOR_DIR}
      - INDEX_NAME=${INDEX_NAME}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - EMBEDDINGS_PROVIDER=${EMBEDDINGS_PROVIDER}
      - EMBEDDINGS_MODEL=${EMBEDDINGS_MODEL}
      - HF_EMBED_MODEL=${HF_EMBED_MODEL}

  emotion-api:
    build:
      context: .
      dockerfile: services/emotion_api/Dockerfile
    container_name: emotion-api
    ports:
      - "8003:8000"
    environment:
      - SERVICE_MODE=local
      - HF_REPO_ID=${HF_REPO_ID}
      - LLM_MODEL=${LLM_MODEL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}

  agent-api:
    build:
      context: .
      dockerfile: services/agent_api/Dockerfile
    volumes:
      - ./.faiss_vs:/app/.faiss_vs
    container_name: agent-api
    depends_on:
      - rag-api
      - emotion-api
    ports:
      - "8001:8000"
    environment:
      - SERVICE_MODE=${SERVICE_MODE}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - LLM_MODEL=${LLM_MODEL}
      - RAG_URL=${RAG_URL}
      - EMOTION_URL=${EMOTION_URL}

  telegram-mcp:
    build:
      context: .
      dockerfile: services/mcp_telegram/Dockerfile.mcp
    container_name: telegram-mcp
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - HOST=${HOST}
      - PORT=${PORT}
      - HTTP_PATH=${HTTP_PATH}
    ports:
      - "8081:8081"
    restart: unless-stopped

  telegram-agent-bridge:
    build:
      context: .
      dockerfile: services/mcp_telegram/Dockerfile.bridge
    container_name: telegram-agent-bridge
    depends_on:
      - telegram-mcp
      - agent-api
    environment:
      - TELEGRAM_MCP_URL=${TELEGRAM_MCP_URL}
      - AGENT_API_URL=${AGENT_API_URL}
      - AGENT_CHAT_PATH=${AGENT_CHAT_PATH}
      - AGENT_MEM_PATH=${AGENT_MEM_PATH}
      - AGENT_CLEAR_PATH=${AGENT_CLEAR_PATH}
      - TELEGRAM_POLL_TIMEOUT=${TELEGRAM_POLL_TIMEOUT}
    restart: unless-stopped

networks:
  default:
    name: agent-net